@settings(defaultLengthUnit = mm)

padSketch = startSketchOn(XY)
  |> circle(center = [0, 0], radius = 32)
padExtrude = extrude(padSketch, length = 5)

stemSketch = startSketchOn(padExtrude, face = END)
  |> circle(center = [0, 0], radius = 2.5)
stemExtrude = extrude(stemSketch, length = 7.1)

ballSketch = startSketchOn(stemExtrude, face = END)
  |> startProfile(at = [0, 0])
  |> line(end = [-5.35, 0])
  |> arc(angleEnd = 0, angleStart = 180, radius = 5.35)
  |> close()
ballRevolve = revolve(ballSketch, axis = X)
  |> appearance(color = "#FF1111")

// TODO: union([padExtrude, stemExtrude, ballRevolve])

ballRevolve